### PR TITLE
Allow --config to load from file:// locations

### PR DESCRIPTION
**Pull request by benley**
Does this look like a reasonable idea?  If so I'll also update the docs to match.

### CODE REVIEW

**Comment by ThanosBaskous** [comment]
I think that's fine, and if you update the docs as well, I'll be happy to merge.

My original thought was to force all configuration to live at the command line so that it is easily discoverable / diffable through the Aurora web interface and API. I suppose the same thing could be accomplished with a "config generator" aurora process that writes the file before the aurproxy_setup or aurproxy Aurora processes are started.

Anyways, that's not a constraint that's necessary to impose on everyone that uses this tool, so I'm fine with the change.

Thanks for contributing!

**Comment by benley** [comment]
Updated the --help text, but I didn't see a great place for this tidbit in README.md.

**Comment by ThanosBaskous** [comment]
:+1:

**Comment by benley** [comment]
:D

**Pull request merged**
